### PR TITLE
Update the UI based on new designs

### PR DESCRIPTION
**Pull request by Clarity-89**
- Update the UI based on Figma designs
- Remove react-terminal package and styles to simplify the code
- Separate Header and Navigation
- Debounce the editor onChange calls to improve performance

Screenshots: 
Screenshot 2023-06-01 at 14 00 50
Screenshot 2023-06-01 at 14 01 08

Screen recording: 

https://github.com/grafana/play-thema/assets/8878045/6eabd074-4d80-4927-a18f-efa0ebf06015

### CODE REVIEW

**Comment by breitreiter** [comment]
Looks good! Would like to see some minor style tweaks to bring it closer to the Figma version:
image

**Comment by Clarity-89** [comment]
Updated the UI based on suggestions. 

Screenshot 2023-06-02 at 9 17 23
Screenshot 2023-06-02 at 9 17 50

**Comment by joanlopez** [comment]
I've been playing a bit with the new changes and they look really really nice, thanks you both @breitreiter and @Clarity-89 for the work! I'd be happy to merge it as-is now, but here's few minor comments I have after my experience:

- Would make sense to set a comment as the default content for the input data editor, similarly to the lineage one? 
I feel that comment is nice way of giving instructions to the user, but now I feel like it might be more consistent and coherent to have "instructions" in both editors. Another idea could be to leave the comment but with some example commented, as below:

  ```yaml
  // Paste or type a JSON document here.
  // You can also load an example from the toolbar.
  //
  // {
  //   "firstfield": "value"
  // }
  //
  ```

- I lack some contrast between the color of the error messages and the background on the light theme (see the screenshot below), it is readable but not very sight friendly:

  image
 

- (_**Bonus track**_, _definitely for another PR_) I'd love to replace the current GitHub logo on the top right corner by the one commonly used to star the repository:

  image
    vs

  image


In any case, as I mentioned at the beginning of this comment, I'd be happy to merge it as-is and work on these on a separate PR, as you want.

Thanks!!!

**Review by joanlopez — APPROVED** [review]

**Comment by Clarity-89** [comment]
> * **Would make sense to set a comment as the default content for the input data editor, similarly to the lineage one?**
>   I feel that comment is nice way of giving instructions to the user, but now I feel like it might be more consistent and coherent to have "instructions" in both editors. Another idea could be to leave the comment but with some example commented, as below:
>   ```yaml
>   // Paste or type a JSON document here.
>   // You can also load an example from the toolbar.
>   //
>   // {
>   //   "firstfield": "value"
>   // }
>   //
>   ```
> * I **lack some contrast between the color of the error messages and the background** on the light theme (see the screenshot below), it is readable but not very sight friendly:
>   image
> * (_**Bonus track**_, _definitely for another PR_) I'd love to **replace the current GitHub logo** on the top right corner by the one commonly used to star the repository:
>   image
>   vs
>   image
> 
> In any case, as I mentioned at the beginning of this comment, I'd be happy to merge it as-is and work on these on a separate PR, up to you.
> 
> Thanks!!!

Thank for the feedback! I'll add a comment example and check the contrast. 

Not sure about adding the star button. The primary role is to direct users to the GitHub repo and not to make them star it. I personally never click the star button unless I've seen the repo before.

**Comment by joanlopez** [comment]
> Not sure about adding the star button. The primary role is to direct users to the GitHub repo and not to make them star it. I personally never click the star button unless I've seen the repo before. Additionally, it'd look a bit out of place in the current UI.

Fair enough, yeah! Let's revisit that in the future, if needed. Thanks! :)

**Comment by Clarity-89** [comment]
Just realised that comments are not allowed in JSON, which will be highlighted in the editor as an error, so I think it's better to skip those.

**Comment by joanlopez** [comment]
> Just realised that comments are not allowed in JSON, which will be highlighted in the editor as an error, so I think it's better to skip those.

I'd suggest to try with `yaml` as language, in theory YAML is a superset of JSON (so a JSON object should be considered a syntax), and it accepts comments.

**Pull request merged**
