### PR TITLE
Code structure updates

### PR DESCRIPTION
**Pull request by Clarity-89**
Re-arrange the files to resemble more the general Grafana structure. No functional changes. 

- Move the app files to the top level
- Add `devDependencies`
- Add Prettier and format the code
- Remove redundant assets

### CODE REVIEW

**Review by joanlopez — CHANGES_REQUESTED** [review]
Awesome! Thanks for taking care of it @Clarity-89! 💟 

There's just one more missing thing: you'll need to update the CI config at [`deploy.yml`](https://github.com/grafana/play-thema/blob/main/.github/workflows/deploy.yml) according to the code re-org.

**Comment by Clarity-89** [comment]
> Awesome! Thanks for taking care of it @Clarity-89! 💟
> 
> There's just one more missing thing: you'll need to update the CI config at [`deploy.yml`](https://github.com/grafana/play-thema/blob/main/.github/workflows/deploy.yml) according to the code re-org.

Good catch! Btw to run the project, do I need to do anything about the Go code, i.e. compile it? (I think adding Readme with this kind of info would be helpful).

**Comment by joanlopez** [comment]
> Btw to run the project, do I need to do anything about the Go code, i.e. compile it?

Nope, we decided to commit [the WASM artifact](https://github.com/grafana/play-thema/blob/main/app/public/thema.wasm) for now, so build & run the application should be as simple as `yarn install --immutable` and `yarn start`.

Unless, of course, you want to make some changes to the Go code. 
In such case you need to recompile it: `GOOS=js GOARCH=wasm go build -o ./path/to/thema.wasm wasm/*.go`

> (I think adding Readme with this kind of info would be helpful)

I completely agreed! Gonna create an issue and take care of it during the next few days! Thanks! :)

**Comment by undef1nd** [comment]
>Unless, of course, you want to make some changes to the Go code.
In such case you need to recompile it: GOOS=js GOARCH=wasm go build -o ./path/to/thema.wasm wasm/*.go

May be worth adding a makefile?

**Comment by Clarity-89** [comment]
> > Unless, of course, you want to make some changes to the Go code.
> > In such case you need to recompile it: GOOS=js GOARCH=wasm go build -o ./path/to/thema.wasm wasm/*.go
> 
> May be worth adding a makefile?

I think that'd be handy.

**Pull request merged**
